import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
import { Footer } from "./_components/footer";
import AnnouncementBand from "./_components/announcementBand";
import WhatsaapStickyButton from "./_components/whatsaapStickyButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], // Burada hatayı düzelttik
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
      >
        <AnnouncementBand />
        <Navbar />
        <main>{children}</main>
        <Footer />
        <WhatsaapStickyButton />
      </body>
    </html>
  );
}
